#!/bin/sh

SCRIPT=`readlink -f "$0"`
SCRIPTPATH=`dirname "$SCRIPT"`

# read required APIGEE_ vars from aac-token, chosen request 

REQUEST_TYPE=$1

[ -z $REQUEST_TYPE ] && read -p "Request type: " REQUEST_TYPE

# make request
TOKEN=`$SCRIPTPATH/token` sh $SCRIPTPATH/requests/$REQUEST_TYPE
  
