#!/bin/sh

set -e
set -x

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

# read required APIGEE_ vars from aac-token, chosen request 

REQUEST_TYPE=$1

[ -z "$REQUEST_TYPE" ] && printf "Request type: " && read -r REQUEST_TYPE

# make request
TOKEN=$("$SCRIPTPATH"/token) sh "$SCRIPTPATH"/requests/"$REQUEST_TYPE"  
