DEPLOYMENT_SUFFIX="-devrel-pipeline"

SUBSTITUTIONS="_INT_TEST_BASE_PATH=/airports-cicd$DEPLOYMENT_SUFFIX/v1"
SUBSTITUTIONS="$SUBSTITUTIONS,_DEPLOYMENT_ORG=$APIGEE_ORG"
SUBSTITUTIONS="$SUBSTITUTIONS,_DEPLOYMENT_ENV=$APIGEE_ENV"
SUBSTITUTIONS="$SUBSTITUTIONS,_DEPLOYMENT_SUFFIX=$DEPLOYMENT_SUFFIX"

gcloud builds submit --config=cloudbuild-saas.yaml \
  --substitutions=$SUBSTITUTIONS

rm $GCP_SA_KEY_FILE