pipeline {

    agent {
      dockerfile {
        dir 'demos/cicd-jenkins/cicd-demo-v1'
      }
    }

    environment {
        APIGEE_CREDS = credentials('apigee')
        HOME = '.'
        DEMO_SUB_DIR = 'demos/cicd-jenkins/cicd-demo-v1'
        // APIGEE_ORG = 'apigee-org-name' // set org name here or in the jenkins global property at ${JENKINS_URL}/configure
    }

    stages {
        stage('Set Apigee Env and Proxy Suffix') {
          steps {
            script{
              // Master branch for Apigee test environment
              if (env.GIT_BRANCH == "master") {
                  env.APIGEE_DEPLOYMENT_SUFFIX = ""
                  env.MAVEN_PROFILE = "test"
              // Prod branch for Apigee prod environment
              } else if (env.GIT_BRANCH == "prod") {
                  env.APIGEE_DEPLOYMENT_SUFFIX = ""
                  env.MAVEN_PROFILE = "prod"
              // All other branches are deployed as separate proxies with suffix in the test environment
              } else {
                  env.APIGEE_DEPLOYMENT_SUFFIX = env.GIT_BRANCH ? "-" + env.GIT_BRANCH.replaceAll("\\W", "-") : "-jenkins"
                  env.MAVEN_PROFILE = "test"
              }
              println "Proxy Deployment Suffix: " + env.APIGEE_DEPLOYMENT_SUFFIX
            }
          }
        }

        stage('Clean') {
          steps {
            dir(env.DEMO_SUB_DIR) {
              sh "mvn clean"
            }
          }
        }

        stage('Static Code Analysis') {
          steps {
            dir(env.DEMO_SUB_DIR) {
              sh "mvn validate"
            }
          }
        }

        stage('Unit Test') {
          steps {
            dir(env.DEMO_SUB_DIR) {
              sh "./node_modules/nyc/bin/nyc.js --reporter=html --reporter=text ./node_modules/mocha/bin/_mocha ./test/unit"
            }
          }
        }

        stage('Env Config') {
          steps {
            script {
                AUTHOR_EMAIL = sh (
                    script: 'git --no-pager show -s --format=\'%ae\'',
                    returnStdout: true
              ).trim()
            }
            dir(env.DEMO_SUB_DIR) {
              sh "mvn -ntp process-resources -P${env.MAVEN_PROFILE} \
                    -Dcommit=${env.GIT_COMMIT} \
                    -Dbranch=${env.GIT_BRANCH} \
                    -Dauthor=${AUTHOR_EMAIL} \
                    -Ddeployment.suffix=${env.APIGEE_DEPLOYMENT_SUFFIX}"
            }
          }
        }

        stage('Package proxy bundle') {
          steps {
            dir(env.DEMO_SUB_DIR) {
              sh "mvn -ntp apigee-enterprise:configure -P${env.MAVEN_PROFILE} -Ddeployment.suffix=${env.APIGEE_DEPLOYMENT_SUFFIX}"
            }
          }
        }

        stage('Deploy proxy bundle') {
          steps {
            dir(env.DEMO_SUB_DIR) {
              sh "mvn -ntp apigee-enterprise:deploy -P${env.MAVEN_PROFILE} -Dapigee.org=${env.APIGEE_ORG} -Dapigee.username=${APIGEE_CREDS_USR} -Dapigee.password=${APIGEE_CREDS_PSW} -Ddeployment.suffix=${env.APIGEE_DEPLOYMENT_SUFFIX}"
            }
          }
        }

        stage('Functional Test') {
          steps {
            dir(env.DEMO_SUB_DIR) {
              sh "node ./node_modules/cucumber/bin/cucumber-js ./target/test/integration --format json:./target/reports.json"
            }
          }
        }
    }

    post {
      always {
        dir(env.DEMO_SUB_DIR) {
          publishHTML(target: [
                                allowMissing: false,
                                alwaysLinkToLastBuild: false,
                                keepAll: false,
                                reportDir: "coverage",
                                reportFiles: 'index.html',
                                reportName: 'HTML Report'
                              ]
                      )

          step([
                  $class: 'CucumberReportPublisher',
                  fileExcludePattern: '',
                  fileIncludePattern: "**/reports.json",
                  ignoreFailedTests: false,
                  jenkinsBasePath: '',
                  jsonReportDirectory: "target",
                  missingFails: false,
                  parallelTesting: false,
                  pendingFails: false,
                  skippedFails: false,
                  undefinedFails: false
                  ])
        }
      }
    }
}