#!/bin/sh

# Delete Company App
# https://apidocs.apigee.com/management/apis/delete/organizations/%7Borg_name%7D/companies/%7Bcompany_name%7D/apps/%7Bapp_name%7D
set -x
curl -sSf \
  -X DELETE \
  -H "Authorization: Bearer $TOKEN" \
  "https://api.enterprise.apigee.com/v1/organizations/$APIGEE_ORG/companies/$APIGEE_COMPANY/apps/$APIGEE_APP"

