#!/bin/sh

# List Companies
# https://apidocs.apigee.com/management/apis/get/organizations/%7Borg_name%7D/companies

curl -sSf \
  -H "Authorization: Bearer $TOKEN" \
  "https://api.enterprise.apigee.com/v1/organizations/$APIGEE_ORG/companies"

