#!/bin/sh

# Delete Developer App
# https://apidocs.apigee.com/management/apis/delete/organizations/%7Borg_name%7D/developers/%7Bdeveloper_email_or_id%7D/apps/%7Bapp_name%7D

curl -sSf \
  -X DELETE \
  -H "Authorization: Bearer $TOKEN" \
  "https://api.enterprise.apigee.com/v1/organizations/$APIGEE_ORG/developers/$APIGEE_DEVELOPER/apps/$APIGEE_APP"

