#!/bin/sh

# List Developers
# https://apidocs.apigee.com/management/apis/get/organizations/%7Borg_name%7D/developers

curl -sSf \
  -H "Authorization: Bearer $TOKEN" \
  "https://api.enterprise.apigee.com/v1/organizations/$APIGEE_ORG/developers"

