#!/bin/sh

# List API Proxies
# https://apidocs.apigee.com/management/apis/get/organizations/%7Borg_name%7D/apis

curl \
  -H "Authorization: Bearer `./token`" \
  "https://api.enterprise.apigee.com/v1/organizations/$APIGEE_ORG/apis"

