#!/bin/sh

# List API Products
# https://apidocs.apigee.com/management/apis/get/organizations/%7Borg_name%7D/apiproducts

curl -sSf \
  -H "Authorization: Bearer $TOKEN" \
  "https://api.enterprise.apigee.com/v1/organizations/$APIGEE_ORG/apiproducts"

