#!/bin/sh

# Delete API Product
# https://apidocs.apigee.com/management/apis/delete/organizations/%7Borg_name%7D/apiproducts/%7Bapiproduct_name%7D
set -x
curl -sSf \
  -X DELETE \
  -H "Authorization: Bearer $TOKEN" \
  "https://api.enterprise.apigee.com/v1/organizations/$APIGEE_ORG/apiproducts/${APIGEE_PRODUCT}"

