#!/bin/sh

# Delete Shared Flow
# https://apidocs.apigee.com/shared-flow-api/apis/delete/organizations/%7Borg_name%7D/sharedflows/%7Bshared_flow_name%7D

curl -sSf \
  -X DELETE \
  -H "Authorization: Bearer $TOKEN" \
  "https://api.enterprise.apigee.com/v1/organizations/$APIGEE_ORG/sharedflows/$APIGEE_SHARED_FLOW"

