#!/bin/sh

# Delete Shared Flow Deployment
# https://apidocs.apigee.com/shared-flow-api/apis/delete/organizations/%7Borg_name%7D/environments/%7Benv_name%7D/sharedflows/%7Bshared_flow_name%7D/revisions/%7Brevision_number%7D/deployments
set -x 
curl -sSf \
  -X DELETE \
  -H "Authorization: Bearer $TOKEN" \
  "https://api.enterprise.apigee.com/v1/organizations/$APIGEE_ORG/environments/$APIGEE_ENV/sharedflows/$APIGEE_SHARED_FLOW/revisions/$APIGEE_REV/deployments"

